# Generated by Django 3.1.2 on 2020-11-29 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_chatmessage_thread'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='first',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='second',
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='Thread',
        ),
    ]
