# Generated by Django 3.1.2 on 2020-12-01 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20201129_0621'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='enrollment_number',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
