# Generated by Django 3.1.2 on 2020-12-01 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_alumni_enrollment_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='branch',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
